struct Strings {
    static let translations: [String: [String: String]] = [
        "en": [
            "cancel": "Cancel",
            "save": "Save",
            "done": "Done",
            "edit": "Edit",
            "delete": "Delete",
            "male": "Male",
            "female": "Female",
            "tab_litters": "Litters",
            "tab_settings": "Settings",
            "app_title": "Små Tassar",
            "no_litters_title": "No Litters Yet",
            "no_litters_desc": "Tap + to add your first litter.",
            "puppy_singular": "puppy",
            "puppy_plural": "puppies",
            "complete": "Complete",
            "new_litter": "New Litter",
            "edit_litter": "Edit Litter",
            "litter_name": "Litter Name",
            "litter_name_placeholder": "e.g. Litter A",
            "add_puppy": "Add Puppy",
            "mark_complete": "Mark as Complete",
            "reopen_litter": "Reopen Litter",
            "view_charts": "View Charts",
            "view_litter_charts": "View Litter Charts",
            "no_puppies_title": "No Puppies Yet",
            "no_puppies_desc": "Tap \"Add Puppy\" to get started.",
            "add_puppy_title": "Add Puppy",
            "edit_puppy_title": "Edit Puppy",
            "name_optional": "Name (optional)",
            "collar_color": "Collar Color",
            "pick_a_color": "Pick a color",
            "sex": "Sex",
            "birth_weight_grams": "Birth Weight (grams)",
            "birth_weight_placeholder": "e.g. 450",
            "birth_date_time": "Birth Date & Time",
            "puppy_details": "Puppy Details",
            "born": "Born:",
            "birth_weight_label": "Birth weight:",
            "weight_over_time": "Weight Over Time",
            "weight_entries": "Weight Entries",
            "birth_tag": "(birth)",
            "no_weight_updates": "No weight updates yet.",
            "add_weight": "Add Weight",
            "edit_weight": "Edit Weight",
            "date_time": "Date & Time",
            "weight_grams": "Weight (grams)",
            "weight_placeholder": "e.g. 520",
            "litter_charts": "Litter Charts",
            "no_puppies_charts_title": "No Puppies",
            "no_puppies_charts_desc": "Add puppies to see charts.",
            "weight_gain": "Weight Gain",
            "since_birth": "Since birth",
            "last_update": "Last update",
            "settings": "Settings",
            "language": "Language",
        ],
        "sv": [
            "cancel": "Avbryt",
            "save": "Spara",
            "done": "Klar",
            "edit": "Redigera",
            "delete": "Radera",
            "male": "Hane",
            "female": "Tik",
            "tab_litters": "Kullar",
            "tab_settings": "Inställningar",
            "app_title": "Små Tassar",
            "no_litters_title": "Inga kullar än",
            "no_litters_desc": "Tryck + för att lägga till din första kull.",
            "puppy_singular": "valp",
            "puppy_plural": "valpar",
            "complete": "Klar",
            "new_litter": "Ny kull",
            "edit_litter": "Redigera kull",
            "litter_name": "Kullnamn",
            "litter_name_placeholder": "t.ex. Kull A",
            "add_puppy": "Lägg till valp",
            "mark_complete": "Markera som klar",
            "reopen_litter": "Återöppna kull",
            "view_charts": "Se diagram",
            "view_litter_charts": "Se kulldiagram",
            "no_puppies_title": "Inga valpar än",
            "no_puppies_desc": "Tryck \"Lägg till valp\" för att börja.",
            "add_puppy_title": "Lägg till valp",
            "edit_puppy_title": "Redigera valp",
            "name_optional": "Namn (valfritt)",
            "collar_color": "Halsbandfärg",
            "pick_a_color": "Välj en färg",
            "sex": "Kön",
            "birth_weight_grams": "Födslovikt (gram)",
            "birth_weight_placeholder": "t.ex. 450",
            "birth_date_time": "Datum och tid för födseln",
            "puppy_details": "Valp",
            "born": "Född:",
            "birth_weight_label": "Födslovikt:",
            "weight_over_time": "Viktutveckling",
            "weight_entries": "Viktanteckningar",
            "birth_tag": "(födseln)",
            "no_weight_updates": "Inga viktuppdateringar än.",
            "add_weight": "Lägg till vikt",
            "edit_weight": "Redigera vikt",
            "date_time": "Datum och tid",
            "weight_grams": "Vikt (gram)",
            "weight_placeholder": "t.ex. 520",
            "litter_charts": "Kulldiagram",
            "no_puppies_charts_title": "Inga valpar",
            "no_puppies_charts_desc": "Lägg till valpar för att se diagram.",
            "weight_gain": "Viktökning",
            "since_birth": "Sedan födseln",
            "last_update": "Senaste uppdatering",
            "settings": "Inställningar",
            "language": "Språk",
        ],
    ]
}
